apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: user-admin
  name: example-backend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: example-backend
    spec:
      containers:
      - name: example-backend
        image: aws/example-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
   